name: Create Azure Resources and Deploy App

on:
  workflow_dispatch:

jobs:
  create:
    runs-on: ubuntu-latest

    steps:
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create Azure Resources
      run: |
        az group create --name ${{ env.RESOURCE_GROUP }} --location ${{ env.LOCATION }}
        az appservice plan create --name ${{ env.PLAN_NAME }} --resource-group ${{ env.RESOURCE_GROUP }} --sku F1 --is-linux
        az webapp create --resource-group ${{ env.RESOURCE_GROUP }} --plan ${{ env.PLAN_NAME }} --name ${{ env.APP_NAME }} --runtime "NODE|20-lts" --startup-file "npm start"
